### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Laboratory** [Glavin001/atom-coffeescript-preview#14]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.161.0
**System**: Mac OS X 10.10.1
**Thrown From**: [coffeescript-preview](https://github.com/Glavin001/atom-coffeescript-preview) package, v1.0.0
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Users/Laboratory/.atom/packages/coffeescript-preview/lib/coffeescript-preview-view.coffee:146

TypeError: undefined is not a function
  at CoffeePreviewView.module.exports.CoffeePreviewView.renderHTMLCode (/Users/Laboratory/.atom/packages/coffeescript-preview/lib/coffeescript-preview-view.coffee:146:18)
  at CoffeePreviewView.renderHTMLCode (/Users/Laboratory/.atom/packages/coffeescript-preview/lib/coffeescript-preview-view.coffee:1:1)
  at later (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:724:25)

```

/cc @atom/core

**Comment by Glavin001** [comment]
This package has long since been deprecated. Please use the latest package, https://github.com/Glavin001/atom-preview

If you have problems with atom Preview then let me know there. Thanks.

**Comment by Laboratory** [comment]
Install Error

``` bash
npm http 304 https://registry.npmjs.org/netmask
npm ERR! git fetch -a origin (git://github.com/ariya/esprima.git) fatal: unable to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/ariya/esprima.git) github.com[0: 192.30.252.128]: errno=Connection refused
npm http GET https://registry.npmjs.org/defs
npm ERR! Error: Command failed: fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Socket.<anonymous> (child_process.js:969:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:465:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/Laboratory/.atom/.apmrc" "install" "/Users/Laboratory/.atom/.node-gyp/.atom/.apm/preview/0.13.4/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /private/var/folders/fs/m5gxr4vj6xqg6fcvl5kd3m8r0000gn/T/apm-install-dir-1141118-20336-1drx8pz
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm http 304 https://registry.npmjs.org/defs
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/fs/m5gxr4vj6xqg6fcvl5kd3m8r0000gn/T/apm-install-dir-1141118-20336-1drx8pz/npm-debug.log
npm ERR! not ok code 0
```
